### ISSUE TITLE
Support YAML CodeChecker configuration file

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#3554]
Multiple subcommands have a `--config` option which allow the configuration from an explicit configuration file. The parameters in the config file will be emplaced as command line arguments. Now we support only `JSON` format:
```json
{
  "analyze": [
    "--enable=core.DivideZero",
    "--enable=core.CallAndMessage",
    "--analyzer-config",
    "clangsa:unroll-loops=true",
    "--checker-config",
    "clang-tidy:google-readability-function-size.StatementThreshold=100"
    "--report-hash", "context-free-v2"
    "--verbose=debug",
    "--clean"
  ],
  "parse": [
    "--trim-path-prefix",
    "/$HOME/workspace"
  ],
  "server": [
    "--workspace=$HOME/workspace",
    "--port=9090"
  ],
  "store": [
    "--name=run_name",
    "--tag=my_tag",
    "--url=http://codechecker.my:9090/MyProduct"
  ]
}
```

The limitation of this format is that we can't add comments in this file for example why we enabled/disabled a checker, why an option is important etc.

It would be good to support YAML format too where we can add comments:
```yml
version: 1

analyzer:
  # Enable/disable checkers.
  - --enable core.DivideZero
  - --enable core.CallAndMessage
  # Analyzer configurations.
  - --analyzer-config clangsa:unroll-loops=true
  - --checker-config clang-tidy:google-readability-function-size.StatementThreshold=100
  # Optional options.
  - --report-hash context-free-v2
  - --verbose debug
  - --clean

parse:
  - --trim-path-prefix /$HOME/workspace

server:
  - --workspace $HOME/workspace"
  - --port 9090"

store:
  - --name run_name
  - --tag my_tag
  - --url http://codechecker.my:9090/MyProduct

```
