### ISSUE TITLE
Does clang-tidy support cross translation unit ?

### ISSUE THREAD

**Issue by xiaodiRan** [Ericsson/codechecker#3679]
I noticed the feature in website: 
Executes [Clang-Tidy](http://clang.llvm.org/extra/clang-tidy/) and [Clang Static Analyzer](http://clang-analyzer.llvm.org/) with Cross-Translation Unit analysis, Statistical Analysis (when checkers are available).
But I tested CTU for clang-tidy, it doesn't look like it's working。

# Detailed testing process

```
main.cpp
int foo();
int aa(){
    throw "D";
    return 0;
}
int main(){
    auto t=3/foo();
    return foo();
}
```
```
foo.cpp
int foo(){
    throw "haha";
    return 1;
}
```
```
.clang-tidy
Checks: '-*,bugprone-exception-escape'
CheckOptions:
  - key: bugprone-exception-escape.FunctionsThatShouldNotThrow
    value: 'main'
HeaderFilterRegex: '.*'
```
```
CodeChecker analyze --ctu ./compile_commands.json -o ./reports/ --analyzer-config 'clang-tidy:take-config-from-directory=true'
git tag info :2cb25fc-tainted 
```
